# Generated by Django 3.2.5 on 2022-04-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('1', 'הנדסת תוכנה'), ('2', 'הנדסת בניין'), ('3', 'הנדסת מכונות'), ('4', 'הנדסת חשמל')], default='1', max_length=30)),
                ('year', models.CharField(choices=[('1', 'שנה א'), ('2', 'שנה ב'), ('3', 'שנה ג'), ('4', 'שנה ד')], default='1', max_length=30)),
                ('semester', models.CharField(choices=[('1', 'סמסטר א'), ('2', 'סמסטר ב'), ('3', 'סמסטר קיץ')], default='1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHW', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.course')),
            ],
        ),
        migrations.CreateModel(
            name='fiels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=30)),
                ('home_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.homework')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.department'),
        ),
    ]
