# Generated by Django 3.2.5 on 2022-04-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', 'סמסטר א'), ('2', 'סמסטר ב'), ('3', 'סמסטר קיץ')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('1', 'שנה א'), ('2', 'שנה ב'), ('3', 'שנה ג'), ('4', 'שנה ד')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('1', 'הנדסת תוכנה'), ('2', 'הנדסת בניין'), ('3', 'הנדסת מכונות'), ('4', 'הנדסת חשמל')], default='1', max_length=30),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
