# Generated by Django 3.2.5 on 2022-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220419_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='nameHW',
            new_name='nameFile',
        ),
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.DeleteModel(
            name='fiels',
        ),
    ]
