# Generated by Django 3.2.5 on 2022-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20220420_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
