# Generated by Django 3.2.5 on 2022-04-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
        migrations.CreateModel(
            name='Kind_Of_HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=30)),
                ('lecturers_notebook', models.CharField(max_length=30)),
                ('practice_notebook', models.CharField(max_length=30)),
                ('zoom', models.CharField(max_length=30)),
                ('youtube', models.CharField(max_length=30)),
                ('homeworks', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.course')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='kind_of_homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.kind_of_homework'),
        ),
    ]
