# Generated by Django 3.2.5 on 2022-04-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20220421_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfHomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(default='מבחנים', max_length=30)),
                ('lecturers_notebook', models.CharField(default='הרצאות', max_length=30)),
                ('practice_notebook', models.CharField(default='תרגולים', max_length=30)),
                ('zoom', models.CharField(default='Zoom', max_length=30)),
                ('youtube', models.CharField(default='YouTube', max_length=30)),
                ('homeworks', models.CharField(default='עבודות בית', max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.course')),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='kind_of_homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.kindofhomework'),
        ),
        migrations.DeleteModel(
            name='Kind_Of_HomeWork',
        ),
    ]
