# Generated by Django 3.2.5 on 2022-04-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20220421_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='kind_of_homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.course'),
        ),
        migrations.DeleteModel(
            name='KindOfHomeWork',
        ),
    ]
