# Generated by Django 3.2.5 on 2022-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_course_kind_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kind_of',
            field=models.CharField(choices=[('1', 'הרצאות'), ('2', 'תרגולים'), ('3', 'עבודות בית'), ('3', 'מבחנים'), ('5', 'YouTube'), ('6', 'Zoom')], default='1', max_length=30),
        ),
    ]
