# Generated by Django 3.2.5 on 2022-04-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_youtubevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='index',
        ),
    ]
