# Generated by Django 3.2.5 on 2022-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
