# Generated by Django 3.2.5 on 2022-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220420_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='imag_profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='imag_profile',
        ),
        migrations.AddField(
            model_name='user',
            name='imag_profile',
            field=models.ImageField(default='defProfile.png', null=True, upload_to='images_profiles'),
        ),
    ]
