# Generated by Django 3.2.5 on 2022-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='permissions',
            field=models.BooleanField(default=True),
        ),
    ]
