# Generated by Django 3.2.5 on 2022-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.BooleanField(default=True),
        ),
    ]
