# Generated by Django 3.2.5 on 2022-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('1', 'הנדסת תוכנה'), ('2', 'הנדסת בניין'), ('3', 'הנדסת מכונות'), ('4', 'הנדסת חשמל'), ('5', 'הנדסה כימית')], default='1', max_length=30),
        ),
    ]
