pipeline {
    agent none
    stages{
        stage('Install requirements'){
            agent{
                docker{
                    image 'python:3.7'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]){
                    dir("jenkins") {
			sh 'python -m pip install --upgrade pip --user'
			sh 'python -m pip install -r requirements.txt'
		}
                    dir("Estudy_Project") {
			sh 'pip install django-recaptcha'
			sh 'pip install django-phonenumber-field'
			sh 'pip install coverage'
			sh 'python manage.py makemigrations'
			sh 'python manage.py migrate'
		}
                    sh 'python -m pip install django==2.1.15'
                }
            }
        }
        stage('Compile'){
            agent{
                docker{
                    image 'python:3.7'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]){
			 sh 'python -m compileall TEAM_15_ESTUDY//'//manage.py'
                    	 sh 'pip install django_jenkins'
                }
            }
        }
        stage('Tests'){
            agent{
                docker{
                    image 'python:3.7'
                }
            }
            steps{
		 withEnv(["HOME=${env.WORKSPACE}"]){
		    dir("Estudy_Project"){
			   sh 'python -m coverage run manage.py test && coverage report'
                    }
		}
            }
         }
    }
}
